### ISSUE TITLE
'Laravel\Spark\Providers\SparkServiceProvider' not found

### ISSUE THREAD

**Issue by Wolrab1** [laravel/spark#153]
Anyone else getting this issue on install?  

Problem 1
    - Installation request for laravel/spark ^0.2.3 -> satisfiable by laravel/sp
ark[v0.2.3].
    - laravel/spark v0.2.3 requires laravel/cashier ~6.0 -> no matching package
found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found

**Comment by austinkregel** [comment]
Is this a fresh install (new laravel project)?
Was this the first time you tried installing spark for this project?

**Comment by Wolrab1** [comment]
Yea both new laravel project and spark install, I've followed your instructions but on this occasion it didn't do anything for me.

**Comment by austinkregel** [comment]
What do you mean it didn't do anything for you :confused: ? Did it not fail again :smile:  or did it fail the same way again :tired_face: ?

When I was creating the instructions in #149, it only ever gave me that exception when it failed and I tried installing and it again. So I'd try

**Comment by Wolrab1** [comment]
Sorry @austinkregel here the new set of errors after following instructions - unsure what's going on here -

C:\Users\wolrab1\Desktop\App>spark install
Using version ^1.0@dev for laravel/spark
./composer.json has been updated
> php artisan clear-compiled

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found

Script php artisan clear-compiled handling the pre-update-cmd event returned wit
h an error

  [RuntimeException]
  Error Output:

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update]
[--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-
packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packag
es>]...

**Comment by Wolrab1** [comment]
I should also mention in my vendor folder I don't have a directory for spark :/

**Comment by austinkregel** [comment]
In this case, it means that you have `Laravel\Spark\Providers\SparkServiceProvider::class` in your `config/app.php` file probably somewhere around line 150. 

You should be able to delete that line and try again with that project, or start fresh and try again all together. :smile:

**Comment by Wolrab1** [comment]
Let me give that ago

**Comment by Wolrab1** [comment]
Brilliant! thanks man - seem to be a bit further now.. when I run the php artisan serve command I get the following when visiting: localhost:8000

**Comment by Wolrab1** [comment]
I can confirm though that those files are indeed in the directory, i've tried the php artisan vendor:publish and re-routing the files but still the same errors

**Comment by olezko46** [comment]
The same problem

**Comment by Wolrab1** [comment]
ok, seems the issues have been solved.. Just to recap on what i've done.

- Fresh install of laravel
- Amend the fresh install of laravel composer.json file to include
  "minimum-stability" : "dev",
  "prefer-stable" : true 
- in cmd run spark install
- Copy and paste the following and save as a new model called BaseUser.php

<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class BaseUser extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}
- once saved, amend the user.php model and edit the 8th line as per @austinkregel comments in article #149, change the line: use Illuminate\Foundation\Auth\User as BaseUser; to App\BaseUser;
- Run gulp in the cmd, this should compile all the files for you.
- Finally run php artisan serve to view the landing page.

Tips: if you find gulp doesnt work, you'll need to install elixir in your project: http://laravel.com/docs/5.1/elixir

**Comment by austinkregel** [comment]
Glad to see that it helped you :)

**Comment by Zarthus** [comment]
Likely partially caused by https://github.com/laravel/spark/commit/8b9b72b1f67be2f4a439a0d3650bd3f76e05795e - the install never finished due to an error, hence the files are never copied. 

You can install laravel spark v0.2.2 explicitly until a new version is released.

**Comment by tiggreen** [comment]
Is this issue still valid? I just did fresh `spark` installation using README and I keep getting this

```shell
PHP Fatal error:  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found in /sites/mockdown.me/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
                                    
  [Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found  
```

Anyone figured how to get over this? Thanks a lot!

**Comment by srmklive** [comment]
Here is how i corrected this issue while installing Spark in Laravel 5.1:

* First installed Laravel Cashier 6.0 by adding following line to composer.json file:
```
composer require laravel/cashier:~6.0.0-beta4
```

* Created file **User.php** in **vendor//laravel/framework/Illuminate/Foundation/Auth** folder. Copied the code from here:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/User.php

* After this i installed spark:
```
spark install
```

you will see an error like this:
```
  [ErrorException]                                                             
  copy(/var/www/html/spark/vendor/laravel/spark/resources/stubs/database/migr  
  ations/2014_10_12_100000_create_subscriptions_tables.php): failed to open s  
  tream: No such file or directory  
```

this is because a problem with **php artisan spark:install** command. 

* To correct the above issue, open the **vendor/laravel/spark/app/Console/Install.php** file, and edit the code on line 176-178 from this:
```
copy(
    SPARK_PATH.'/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_tables.php',
    database_path('migrations/'.date('Y_m_d_His').'_create_subscriptions_tables.php')
);
```
to
```
copy(
    SPARK_PATH.'/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_table.php',
    database_path('migrations/'.date('Y_m_d_His').'_create_subscriptions_table.php')
);
```

Now run the **spark install** again, this will correct the issue.

**Comment by tiggreen** [comment]
Sorry but this didn't fix my issue. I still get the same error.

**Comment by srmklive** [comment]
@tiggreen i first created a new laravel app, then performed all the steps mentioned in my last comment..

**Comment by austinkregel** [comment]
@tiggreen I wrote a guide in [another issue](https://github.com/laravel/spark/issues/149#issuecomment-162233011) about how to resolve this issue.

**Comment by kjfdebruin** [comment]
@srmklive Thank you very much! This solved the issue on my side.

**Comment by tiggreen** [comment]
@austinkregel does your solution work only for laravel 5.2?

**Comment by austinkregel** [comment]
@tiggreen My solution is for Laravel 5.1. It's to fix the issues that had appeared at the time

**Comment by Sarav-S** [comment]
@austinkregel I have installed laravel 5.2 and tried installing spark. I got

    Class 'Illuminate\Routing\ControllerServiceProvider' not found 

error. Which I filed in https://github.com/laravel/spark/issues/161. After following https://github.com/laravel/spark/issues/161#issuecomment-167377641 I was able to eliminate 

        Class 'Illuminate\Routing\ControllerServiceProvider' not found 

error, but instead getting 

    [Symfony\Component\Debug\Exception\FatalErrorException]         
    Class 'Laravel\Spark\Providers\SparkServiceProvider' not found

How to resolve this?

**Comment by austinkregel** [comment]
Is it a fresh install of Laravel 5.2? Or are you upgrading from 5.1?

**Comment by austinkregel** [comment]
@Sarav-S The best way to solve this is removing the project and reinstalling everything. I know it's a pain, but it's far easier than hunting for what spark did and didn't copy over. 

Once you remove the project and reinstall it you should be to get the `Illuminate\Routing\ControllerServiceProvider`. I just did a fresh install after updating my global composer packages and recieved the `Illuminate\Routing\ControllerServiceProvider` error.
